name: validate debian yaml files

on: 
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 20 * * *'
jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: validate debian yaml files
      run: |
        sudo apt install python3-pip
        sudo apt install python3-setuptools
        sudo pip3 install virtualenv
        cd scripts/files-validator/
        python3 debian_validator.py $GITHUB_WORKSPACE/data/
